# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: true
        server_name: '%env(BRAND_NAME)%'
        issuer: '%env(BRAND_NAME)%'
        template: admin/security/2fa_form.html.twig    # Custom template rendered for the /2fa page
